"use client";
import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { useAuth } from "@/context/AuthContext";
import { supabase } from "@/lib/supabase";
import type { Event, Comment, Child, FamilyMember, Category, Visibility, ChildRecord, ChildRecordHistory } from "@/types/app";

export const AVATAR_COLORS = [
  { value: "bg-pink-400",   label: "ピンク"   },
  { value: "bg-blue-400",   label: "ブルー"   },
  { value: "bg-green-400",  label: "グリーン" },
  { value: "bg-yellow-400", label: "イエロー" },
  { value: "bg-purple-400", label: "パープル" },
  { value: "bg-orange-400", label: "オレンジ" },
];

type NewEventData = Omit<Event, "id" | "likeCount" | "commentCount" | "likedByMe" | "comments">;

interface EventsContextValue {
  events: Event[];
  children: Child[];
  records: ChildRecord[];
  dataLoading: boolean;
  addEvent: (event: NewEventData) => Promise<void>;
  addComment: (eventId: string, text: string, author: FamilyMember) => Promise<void>;
  toggleLike: (eventId: string) => Promise<void>;
  addChild: (name: string, birthday: string, avatarColor: string) => Promise<void>;
  removeChild: (id: string) => Promise<void>;
  updateEvent: (id: string, data: Partial<NewEventData>) => Promise<void>;
  deleteEvent: (id: string) => Promise<void>;
  saveChildRecord: (childId: string, data: Partial<ChildRecord>) => Promise<void>;
  getRecordHistory: (recordId: string) => Promise<ChildRecordHistory[]>;
}

const EventsContext = createContext<EventsContextValue | null>(null);

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function rowToEvent(row: any): Event {
  return {
    id: row.id,
    date: row.date,
    category: row.category as Category,
    title: row.title,
    diary: row.diary ?? undefined,
    visibility: row.visibility as Visibility,
    childrenIds: row.children_ids ?? [],
    createdBy: row.created_by ?? { id: "", name: "", displayName: "", role: "parent" },
    photos: row.photos ?? [],
    likeCount: row.like_count ?? 0,
    commentCount: row.comment_count ?? 0,
    likedByMe: row.liked_by_me ?? false,
    comments: row.comments ?? [],
    autoGenerated: row.auto_generated ?? false,
    sourceChildId: row.source_child_id ?? undefined,
  };
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function rowToChild(row: any): Child {
  return {
    id: row.id,
    name: row.name,
    birthday: row.birthday ?? undefined,
    avatarColor: row.avatar_color,
  };
}

export function EventsProvider({ children: providerChildren }: { children: ReactNode }) {
  const { user }   = useAuth();
  const [events,   setEvents]      = useState<Event[]>([]);
  const [children, setChildren]    = useState<Child[]>([]);
  const [records,  setRecords]     = useState<ChildRecord[]>([]);
  const [dataLoading, setDataLoading] = useState(false);

  // Supabase からデータ読み込み（ユーザーが変わるたびに再取得）
  useEffect(() => {
    if (!user) {
      setEvents([]);
      setChildren([]);
      return;
    }
    const load = async () => {
      setDataLoading(true);
      const [evRes, chRes, recRes] = await Promise.all([
        supabase.from("events").select("*").eq("user_id", user.id).order("created_at", { ascending: false }),
        supabase.from("children").select("*").eq("user_id", user.id).order("created_at", { ascending: true }),
        supabase.from("child_records").select("*").eq("user_id", user.id),
      ]);
      if (evRes.data) setEvents(evRes.data.map(rowToEvent));
      if (chRes.data) {
        setChildren(chRes.data.map(rowToChild));

        // 各子供について、誕生日イベントが既に存在するか確認
        for (const child of chRes.data) {
          if (child.birthday) {
            const existingBday = evRes.data?.some(
              (e) => e.source_child_id === child.id && e.auto_generated
            );
            // 存在しない場合は自動生成
            if (!existingBday) {
              await registerBirthdayEvent({
                id: child.id,
                name: child.name,
                birthday: child.birthday,
                avatarColor: child.avatar_color,
              });
            }
          }
        }
      }
      if (recRes.data) {
        setRecords(recRes.data.map((row) => ({
          id: row.id,
          childId: row.child_id,
          likes: row.likes,
          dislikes: row.dislikes,
          allergies: row.allergies,
          interests: row.interests,
          createdAt: row.created_at,
          updatedAt: row.updated_at,
        })));
      }
      setDataLoading(false);
    };
    load();
  }, [user?.id]);

  const addEvent = async (data: NewEventData) => {
    const newEvent: Event = {
      ...data,
      id: `evt-${Date.now()}`,
      likeCount: 0,
      commentCount: 0,
      likedByMe: false,
      comments: [],
    };
    setEvents((prev) => [newEvent, ...prev]); // 楽観的更新
    await supabase.from("events").insert({
      id: newEvent.id,
      user_id: user?.id ?? "guest",
      date: newEvent.date,
      category: newEvent.category,
      title: newEvent.title,
      diary: newEvent.diary ?? null,
      visibility: newEvent.visibility,
      children_ids: newEvent.childrenIds,
      created_by: newEvent.createdBy,
      photos: newEvent.photos,
      like_count: 0,
      comment_count: 0,
      liked_by_me: false,
      comments: [],
    });
  };

  const addComment = async (eventId: string, text: string, author: FamilyMember) => {
    const comment: Comment = {
      id: `c-${Date.now()}`,
      eventId,
      author,
      text,
      createdAt: new Date().toISOString(),
    };
    setEvents((prev) =>
      prev.map((e) =>
        e.id === eventId
          ? { ...e, comments: [...e.comments, comment], commentCount: e.commentCount + 1 }
          : e
      )
    );
    // DBから最新のコメント配列を取得してから更新
    const { data } = await supabase.from("events").select("comments, comment_count").eq("id", eventId).single();
    if (data) {
      await supabase.from("events").update({
        comments: [...(data.comments as Comment[]), comment],
        comment_count: (data.comment_count as number) + 1,
      }).eq("id", eventId);
    }
  };

  const toggleLike = async (eventId: string) => {
    let newLikedByMe = false;
    let newLikeCount = 0;
    setEvents((prev) =>
      prev.map((e) => {
        if (e.id !== eventId) return e;
        newLikedByMe = !e.likedByMe;
        newLikeCount = e.likedByMe ? e.likeCount - 1 : e.likeCount + 1;
        return { ...e, likedByMe: newLikedByMe, likeCount: newLikeCount };
      })
    );
    await supabase.from("events").update({
      liked_by_me: newLikedByMe,
      like_count: newLikeCount,
    }).eq("id", eventId);
  };

  const addChild = async (name: string, birthday: string, avatarColor: string) => {
    const newChild: Child = {
      id: `child-${Date.now()}`,
      name: name.trim(),
      birthday: birthday || undefined,
      avatarColor,
    };
    setChildren((prev) => [...prev, newChild]);
    await supabase.from("children").insert({
      id: newChild.id,
      user_id: user?.id ?? "guest",
      name: newChild.name,
      birthday: newChild.birthday ?? null,
      avatar_color: newChild.avatarColor,
    });

    // 誕生日がある場合は自動登録
    if (birthday) {
      await registerBirthdayEvent(newChild);
    }
  };

  const removeChild = async (id: string) => {
    setChildren((prev) => prev.filter((c) => c.id !== id));
    await supabase.from("children").delete().eq("id", id);
  };

  const updateEvent = async (id: string, data: Partial<NewEventData>) => {
    // 楽観的更新
    setEvents((prev) =>
      prev.map((e) => e.id === id ? { ...e, ...data } : e)
    );
    // DB 更新
    await supabase.from("events").update({
      ...(data.date && { date: data.date }),
      ...(data.category && { category: data.category }),
      ...(data.title && { title: data.title }),
      ...(data.diary !== undefined && { diary: data.diary ?? null }),
      ...(data.visibility && { visibility: data.visibility }),
      ...(data.childrenIds && { children_ids: data.childrenIds }),
      ...(data.photos && { photos: data.photos }),
    }).eq("id", id);
  };

  const deleteEvent = async (id: string) => {
    // 楽観的更新
    setEvents((prev) => prev.filter((e) => e.id !== id));
    // DB 削除
    await supabase.from("events").delete().eq("id", id);
  };

  const registerBirthdayEvent = async (child: Child) => {
    if (!child.birthday || !user) return;

    const [year, month, day] = child.birthday.split('-');
    const currentYear = new Date().getFullYear();

    // 今年の該当月日
    const birthdayEvent: NewEventData = {
      date: `${currentYear}-${month}-${day}`,
      category: "growth",
      title: `${child.name}の誕生日 🎂`,
      visibility: "all",
      childrenIds: [child.id],
      createdBy: { id: user.id, name: user.name, displayName: user.displayName, role: user.role },
      photos: [],
      diary: undefined,
    };

    // DB 挿入
    await supabase.from("events").insert({
      id: `evt-${Date.now()}`,
      user_id: user.id,
      date: birthdayEvent.date,
      category: birthdayEvent.category,
      title: birthdayEvent.title,
      visibility: birthdayEvent.visibility,
      children_ids: [child.id],
      created_by: birthdayEvent.createdBy,
      photos: [],
      diary: null,
      auto_generated: true,
      source_child_id: child.id,
      like_count: 0,
      comment_count: 0,
      liked_by_me: false,
      comments: [],
    });
  };

  const saveChildRecord = async (childId: string, data: Partial<ChildRecord>) => {
    // 楽観的更新
    const existingRecord = records.find((r) => r.childId === childId);
    if (existingRecord) {
      setRecords((prev) =>
        prev.map((r) =>
          r.childId === childId
            ? { ...r, ...data, updatedAt: new Date().toISOString() }
            : r
        )
      );
    }

    if (!user) return;

    // 既存レコード確認
    const { data: existing } = await supabase
      .from("child_records")
      .select("*")
      .eq("child_id", childId)
      .eq("user_id", user.id)
      .single();

    if (existing) {
      // 更新 + 履歴記録
      await supabase.from("child_records").update({
        likes: data.likes,
        dislikes: data.dislikes,
        allergies: data.allergies,
        interests: data.interests,
        updated_at: new Date().toISOString(),
      }).eq("id", existing.id);

      // 履歴テーブルに記録
      await supabase.from("child_records_history").insert({
        record_id: existing.id,
        likes: data.likes,
        dislikes: data.dislikes,
        allergies: data.allergies,
        interests: data.interests,
        changed_at: new Date().toISOString(),
      });
    } else {
      // 新規作成
      const newRecord: ChildRecord = {
        id: `rec-${Date.now()}`,
        childId,
        ...data,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };
      setRecords((prev) => [...prev, newRecord]);

      await supabase.from("child_records").insert({
        id: newRecord.id,
        user_id: user.id,
        child_id: childId,
        likes: data.likes,
        dislikes: data.dislikes,
        allergies: data.allergies,
        interests: data.interests,
      });
    }
  };

  const getRecordHistory = async (recordId: string): Promise<ChildRecordHistory[]> => {
    const { data } = await supabase
      .from("child_records_history")
      .select("*")
      .eq("record_id", recordId)
      .order("changed_at", { ascending: false });
    return data?.map((row) => ({
      id: row.id,
      recordId: row.record_id,
      likes: row.likes,
      dislikes: row.dislikes,
      allergies: row.allergies,
      interests: row.interests,
      changedAt: row.changed_at,
    })) ?? [];
  };

  return (
    <EventsContext.Provider value={{
      events, children, records, dataLoading,
      addEvent, addComment, toggleLike, addChild, removeChild, updateEvent, deleteEvent, saveChildRecord, getRecordHistory,
    }}>
      {providerChildren}
    </EventsContext.Provider>
  );
}

export function useEvents() {
  const ctx = useContext(EventsContext);
  if (!ctx) throw new Error("useEvents must be used within EventsProvider");
  return ctx;
}
